source "https://rubygems.org"

gemspec

gem 'test-unit', '~> 3.2', '>= 3.2.7'

# Only required for tests with Rack 2.x on Ruby 4.0+
gem 'cgi'
gem 'ostruct'

eval_gemfile File.expand_path("Gemfile.linters", __dir__)
